language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "sam-rosenthal-github"
      token:
        secure: "ff9e52b13fdc1d7579470b4eac2adaa0ad482180"
      
    
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -X
  #-Dsonar.organization=sam-rosenthal-github-Dsonar.host.url=https://sonarcloud.io-Dsonar.login=ff9e52b13fdc1d7579470b4eac2adaa0ad482180
  
