language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "sonarcloud"
    
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  mvn clean 
  mvn org.jacoco:jacoco-maven-plugin:prepare-agent
  mvn package
  #sonar:sonar
  mvn sonar:sonar-Dsonar.organization=sam-rosenthal-github-Dsonar.host.url=https://sonarcloud.io-Dsonar.login=ff9e52b13fdc1d7579470b4eac2adaa0ad482180
  
